[package]
name = "read_write_modbus_tcp_rtu"
version = "0.1.0"
edition = "2021"
authors = ["Chrispine Tinega <hello@chrispinetinega.com>"]

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tokio-modbus = "0.16.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"